### ISSUE TITLE
Adicionar casos de teste da 2ª fase.

### ISSUE THREAD

**Issue by vinii-dev** [larguesa/interfatecs-2023#1]
Vi que a primeira fase tem os casos de teste disponível no repositório, porém na segunda fase não tem. Seria possível adicioná-los?

**Comment by larguesa** [comment]
Sim, Thauan.

Conforme forem disponibilizados para mim, publicarei no repositório.


--
Ricardo Pupo Larguesa


Em sex., 6 de out. de 2023 às 17:42, Thauan Vinicius <
***@***.***> escreveu:

**Comment by larguesa** [comment]
Acabei de publicar:
https://github.com/larguesa/interfatecs-2023/tree/main/2a-fase/test-cases

**Comment by larguesa** [comment]
Casos de teste publicaos na pasta "2a-fase"
